name: Bundle Resourcepack
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - run: npm install

      - name: Extracting Assets
        run: npm run extract

      # - name: Bundling Assets
      #   run: npm run build

      - name: Setting up
        run: |
          mkdir ./build

      - name: Run PackSquash
        uses: ComunidadAylas/PackSquash-action@v2
        with:
          path: temp
          transcode_ogg: false
      
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: Optimized pack
          path: ./

      - name: Hashing Resource Pack
        run: |
          cp ./pack.zip ./build/rp-production.zip
          RPSUM=$(sha1sum build/rp-production.zip | awk '{print toupper($1)}')
          echo "$RPSUM" > build/rp-production.sha1
          echo "🔗 Checksum: $RPSUM"

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
